---
title: "Figures for Lobster-Urchin Functional Resposne"
output: html_document
---

```{r setup, include=T, echo=F}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup}

library("here")
source(here("code","setup.R"))
source(here("code","functions.R"))
source(here("code","clean.R"))
source(here("code","Bayesian_Jags.R"))

```


```{r figure1}

###############################################################################
## Basic plot of number consumed by predator and prey size at max density
##############################################################################

p1 <- df %>%
  filter(density > 24) %>%
ggplot(aes(x = class, y = num_consumed))+
  geom_boxplot(outlier.shape = 4, fill = NA)+
  geom_jitter(aes(color = class), width = 0.3, show.legend = F)+
  scale_color_manual(values = c('#1b9e77','#d95f02','#7570b3','#e7298a'))+
  labs(y = "Number of prey eaten", x = "Predator size category")+
  theme_pubclean()


p2 <- df %>%
  filter(density > 24) %>%
  ggplot(aes(x = treatment, y = num_consumed))+
  geom_boxplot(outlier.shape = 4, fill = NA)+
  geom_jitter(aes(color = treatment), width = 0.3, show.legend = F)+
  scale_color_manual(values = c('#d95f02','#7570b3','#e7298a'))+
  labs(y = "Number of prey eaten", x = "Prey size category")+
  scale_x_discrete(labels = c('large', 'medium', 'small'))+
  theme_pubclean()

fig1 <- cowplot::plot_grid(p1, p2 + labs(y = NULL))


png(here("figures",paste("fig1_", Sys.Date(), ".png", sep = "")), width = 623*1.2, height = 369*1.2)
fig1
dev.off()
```

```{r plotjagsfit}

##########################################################
## Plot Jags output fit to each size combination
##########################################################

mods <- paste("mod", seq(1,12), sep = "") #vector of model names

# Write function to plot fits
plot.jags <- function(model, pred_size, urc_size){
  temp <- df %>% filter(class == pred_size, treatment == urc_size)
  killed <- temp$num_consumed
  initial <- temp$num_offered
  plot(killed ~ jitter(initial),data = temp, xlab="Number of prey",ylab="Number consumed", ylim = c(0,26), main = paste(pred_size, "lobster", "-", strsplit(urc_size, "_")[[1]][2], "urchins"))
  a = MCMCsummary(get(model),params='a')[1] # the alpha estimate here is often bounding up against zero
  h = MCMCsummary(get(model),params='h')[1]
  curve(holling2(x,a,h,P=1,T=1),add=TRUE,col=1,lty=1) #true curve
  
}


# Plot 12 panel of fits

lob.size <- rev(c("small", "medium", "large", "jumbo"))
urc.size <- rev(c("urc_small", "urc_medium", "urc_large"))

#***
#####AS is confused about what "mods" is here - i see a bunch of models in the bayesian fits but not mods? oh okay
#####I see it's below change the order of this code chunk and below to make sure mods is already defined 
#***
  
treat2 <- data.frame(model = mods, lob.size = rep(lob.size, times = 3), urc.size = rep(urc.size, each = 4))
treat2 <- treat2 %>% mutate_all(as.character)

pdf(here("figures",paste("fig2_", Sys.Date(), ".pdf", sep = "")), width = 11, height = 7)
#c(bottom, left, top, right)
d <- par(mfrow = c(3,4), mar = c(2,2,2,2), oma = c(3, 3, 0.5, 0.5))
for(i in 1:nrow(treat2)){
  plot.jags(treat2$model[i], treat2$lob.size[i], treat2$urc.size[i])
}
mtext("Number consumed", side = 1, outer = TRUE, cex = 1.1, line = 1.2, font =2)
mtext("Number of prey offered", side = 2, outer = TRUE, cex = 1.1, line = 1.2, font = 2)
par(d)
dev.off()

```

```{r plotjagsparameters}

##############################################
# Make coefficient style plots of parameter fits
##############################################

#setup

mods <- paste("mod", seq(1,12), sep = "") #vector of model names

mod.coef <- lapply(mods, function(x) {
  MCMCsummary(get(x), params = c("a", "h"))
}) #apply the MCMCsummary() function to extract summaries of a and h for each model

names(mod.coef) <- mods #name the list 

mod.coef <- do.call(rbind, mod.coef)
parameter <- rownames(mod.coef)
mod.coef <- as.data.frame(mod.coef)
row.names(mod.coef) <- NULL
mod.coef$parameter <- parameter
mod.coef$model <- rep(mods, each = 2)

names(mod.coef)[c(3,4,5)] <- c("c2.5", "c50", "c97.5") #fix the name
mod.coef$parameter <- rep(c("a", "h"), times = 12) # add variable for parameter


# make correct labels for each model
treat <- data.frame(model = mods, lob.size = rep(c("jumbo", "large", "medium", "small"), times = 3), urc.size = rep(c("large", "medium", "small"), each = 4))
treat$combo <- paste(treat$lob.size, treat$urc.size, sep = "_")

mod.coef <- mod.coef %>% left_join(treat)

pred.labels <- rev(rep(c("small", "medium", "large", "jumbo"), each = 3))
prey.labels <- rev(rep(c("small", "medium", "large"), times = 4))

# plot coefficients and 95% confidence intervals
coef <- ggplot(mod.coef)+
  geom_linerange(aes(x = as.numeric(as.factor(combo)), ymin = c2.5, ymax = c97.5), lwd = 1) +
  geom_point(aes(x = as.numeric(as.factor(combo)), y = c50), size = 2, lwd = 1, shape = 21)+
  scale_x_continuous(breaks = 1:length(pred.labels), labels = pred.labels, 
                     sec.axis = sec_axis(~., breaks = 1:length(pred.labels), 
                                         labels = prey.labels)) +
  coord_flip() +
  facet_wrap(~parameter, ncol = 1)+
  labs(y = "")+
  theme_bw()+
  theme(axis.title.y = element_blank(), axis.text = element_text(size = 12), axis.title = element_text(size = 14))

# pdf(paste("figures/fig3_", Sys.Date(), ".pdf", sep = ""), width = 6.5 , height = 10)
# coef
# dev.off()


#Two panel with facet wrapping

pa <- mod.coef %>% filter(parameter == "a") %>%
  mutate(urc.size, urc.size = paste(urc.size, "prey", sep = " ")) %>%
ggplot()+
  geom_linerange(aes(x = lob.size, ymin = c2.5, ymax = c97.5), lwd = 1) +
  geom_point(aes(x = lob.size, y = c50), size = 2, lwd = 1, shape = 21)+
  scale_y_continuous(breaks = seq(0, 1.2, by = 0.4), labels = seq(0, 1.2, by = 0.4) ) +
  coord_flip() +
  facet_wrap(~urc.size)+
  labs(y = "", title = "Attack rate")+
  #coord_capped_cart(bottom='both', left='both')+
  theme_bw()+
  theme(axis.title.y = element_blank(), axis.text = element_text(size = 12), axis.title = element_text(size = 14))

ph <- mod.coef %>% filter(parameter == "h") %>%
  mutate(urc.size, urc.size = paste(urc.size, "prey", sep = " ")) %>%
ggplot()+
  geom_linerange(aes(x = lob.size, ymin = c2.5, ymax = c97.5), lwd = 1) +
  geom_point(aes(x = lob.size, y = c50), size = 2, lwd = 1, shape = 21)+
  coord_flip() +
  facet_wrap(~urc.size)+
  labs(y = "", title = "Handling time")+
  #coord_capped_cart(bottom='both', left='both')+
  theme_bw()+
  theme(axis.title.y = element_blank(), axis.text = element_text(size = 12), axis.title = element_text(size = 14))

# pdf(paste("figures/fig3_v2_", Sys.Date(), ".pdf", sep = ""), width = 7 , height = 5)
# cowplot::plot_grid(pa,ph, align = "v", ncol = 1)
# dev.off()


####################################
## Build Violin Plot
####################################

#build df to use in plot
out <- list()

for(i in mods){
  temp <- MCMCchains(get(i))[, c("a", "h")]
  out[[i]] <- cbind(temp, names(out[i]))
} #extract information for chains of each model


chains <- as.data.frame(do.call(rbind, out))
names(chains) <- c("a", "h", "model")

chains %>% gather(parameter, estimate, -model) %>%
  left_join(treat) %>%
  
  ggplot()+
  geom_violin(aes(x = combo, y = estimate))+
  scale_x_discrete(labels = pred.labels)+
  #sec_axis(~ . * 1, breaks = 1:length(prey.labels), labels = prey.labels)+
  #geom_boxplot(aes(x = combo, y = estimate), width=0.1)+
  coord_flip() +
  facet_wrap(~parameter, ncol = 1)+
  theme_bw()+
  theme(axis.title.y = element_blank(), axis.text = element_text(size = 12), axis.title = element_text(size = 14))

```

